### PR TITLE
Support --config option via command line

### PR DESCRIPTION
**Pull request by cloverich**
This wasn't working as intended -- passing `--config` to an `npm run` command doesn't pass it through. I think I originally thought `eslint` was reading a local config file for overrides but that doesn't appear to be the case -- unsure how this was working before. Am I overlooking something here?

### CODE REVIEW

**Comment by dpratt** [comment]
Strange - I've been seeing it pull in the project level .eslintrc

**Comment by cloverich** [comment]
I could have sworn it was doing so for web as well, which is why I think i'm overlooking something.

**Comment by pmckinnon** [comment]
Yeah, I thought it was too, and I have definitely used arbitrary args to an `npm run` command before, your comment is confusing are you saying you were using -- followed by --config? Because AFAIK anything you pass on the command line past the npm run command will be appended to the command defined int he scripts section.

Looks good to me otherwise.

**Comment by cloverich** [comment]
I was passing `npm run ojo-test --config .eslintrc`. It looks like based on the [npm issue](https://github.com/npm/npm/issues/3494) like you have to pass `--` first which I was unaware of, e.g.:

`npm run ojo-test -- --config .eslintrc` should work. Explains it eating `--config` when it was not preceded by `--`.

**Pull request merged**
